name: VillagerLobotimizer
version: '${version}'
main: dev.mja00.villagerLobotomizer.VillagerLobotomizer
api-version: '1.21.6'
authors: [ mja00, DereC4 ]
description: A plugin that turns off Villager's brains when they're stuck in a trading hall.
website: https://github.com/mja00/VillagerLobotimizer
folia-supported: true
permissions:
  lobotomy.command:
    description: "Allows the use of the lobotomy command"
    default: op
    children:
      lobotomy.command.info: true
      lobotomy.command.debug: true
      lobotomy.command.wake: true
      lobotomy.command.reload: true
      lobotomy.command.config: true
  lobotomy.command.info:
    description: "Allows /lobotomy info"
    default: op
  lobotomy.command.debug:
    description: "Allows all debug commands"
    default: op
    children:
      lobotomy.command.debug.villager: true
      lobotomy.command.debug.toggle: true
  lobotomy.command.debug.villager:
    description: "Allows /lobotomy debug villager"
    default: op
  lobotomy.command.debug.toggle:
    description: "Allows /lobotomy debug toggle"
    default: op
  lobotomy.command.wake:
    description: "Allows /lobotomy wake"
    default: op
  lobotomy.command.reload:
    description: "Allows /lobotomy reload"
    default: op
  lobotomy.command.config:
    description: "Allows /lobotomy config"
    default: op
