name: VillagerLobotimizer
version: '1.11.2'
main: dev.mja00.villagerLobotomizer.VillagerLobotomizer
api-version: '1.21.6'
authors: [ mja00, DereC4 ]
description: A plugin that turns off Villager's brains when they're stuck in a trading hall.
website: https://github.com/mja00/VillagerLobotimizer
folia-supported: true
permissions:
  lobotomy.command:
    description: "Allows the use of the lobotomy command"
    default: op
