name: Publish to Hangar and Modrinth
# Run this on pushes to main and if there's a tag
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  contents: write


jobs:
  publish:
    runs-on: ubuntu-24.04
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: "gradle"
      # Publish to Hangar using the gradle plugin
      # This outputs: Successfully published VillagerLobotomy version 1.2-snapshot-4f5226c to Hangar: https://hangar.papermc.io/mja00/VillagerLobotomy/versions/1.2-snapshot-4f5226c at the end
      - name: Publish
        id: publish
        env:
          HANGAR_API_KEY: ${{ secrets.HANGAR_API_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          IS_TAGGED_RUN: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          output=$(./gradlew build publishAll --stacktrace)
          echo "$output"
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Parse publish result
        id: parse-publish-result
        run: |
          version=$(echo "${{ steps.publish.outputs.output }}" | grep -E "Successfully published .* version" | sed -E 's/.*version ([^ ]+) to.*/\1/')
          url=$(echo "${{ steps.publish.outputs.output }}" | grep -E "Successfully published .* to Hangar:" | sed -E 's/.*to Hangar: ([^ ]+).*/\1/')
          modrinth_url=$(echo "${{ steps.publish.outputs.output }}" | grep -Eo 'https://modrinth.com/(project|plugin)/[^ ]+/version/[^ ]+')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "modrinth_url=$modrinth_url" >> $GITHUB_OUTPUT
      - name: Get current date in ISO 8601 format
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: "VillagerLobotomy ${{ github.ref_name }}"
          body: |
            ## VillagerLobotomy ${{ steps.parse-publish-result.outputs.version }}
            
            **Released:** ${{ steps.date.outputs.date }}
            
            ### Downloads
            - 📦 [Hangar](${{ steps.parse-publish-result.outputs.url }})
            - 📦 [Modrinth](${{ steps.parse-publish-result.outputs.modrinth_url }})
            
            ### What's Changed
            Check the commits since the last release for detailed changes.
          draft: false
          prerelease: false
          files: |
            build/libs/*.jar
      - name: Announce to Discord
        uses: tsickert/discord-webhook@v6.0.0
        if: startsWith(github.ref, 'refs/tags/') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          username: Villager Lobotomy
          avatar-url: https://cdn.modrinth.com/data/sQ1MQcd2/16cd6db5088b78b41c29cda8eda940f5390efa08.png
          embed-title: "New VillagerLobotimizer update!"
          embed-description: "${{ steps.parse-publish-result.outputs.version }} is now available on Hangar and Modrinth! [Hangar](${{ steps.parse-publish-result.outputs.url }}) | [Modrinth](${{ steps.parse-publish-result.outputs.modrinth_url }})"
          embed-thumbnail-url: https://hangarcdn.papermc.io/avatars/project/3678.webp?v=1
          embed-timestamp: "${{ steps.date.outputs.date }}"
